const SET_LANGUAGE = 'SET_LANGUAGE';
const SAVE_WALLETNAME = 'SAVE_WALLETNAME';
const SAVE_WALLETADDRESS = 'SAVE_WALLETADDRESS';
const KEYSTOREV3 = 'KEYSTOREV3';

export default{
    SET_LANGUAGE,
    SAVE_WALLETNAME,
    SAVE_WALLETADDRESS,
    KEYSTOREV3
}