import { StyleSheet } from 'react-native';


const styles = StyleSheet.create({
    myPage:{
        flex:1,
        // backgroundColor:"yellow",
    },
    myTopBan:{
        backgroundColor:"#528bf7"
    },
    myTopBanTitle:{
        color:"white",
        fontSize:20,
        textAlign:"center",
        height:40,
        lineHeight:40
    },
    myTopBanCon:{
        flexDirection:"row",
        justifyContent:"space-around",
        height:100
    },
    myTopBanConItem:{
        flex:1,
        // borderWidth:1,
        // borderColor:"yellow",
        justifyContent:"center",
        alignItems:"center"
    },
    myTopBanWalleticon:{
        width:25,
        height:27
    },
    myTopBanrecicon:{
        width:30,
        height:25
    },
    myTopBanConItemText:{
        color:"white",
        fontSize:13,
        marginTop:5
    },
    myColsCon:{},
    myColsConPart:{
        marginBottom:10,
        backgroundColor:"white"
    },
    myColsConPartRow:{
        flexDirection:"row",
        alignItems:"stretch",
        height:60
    },
    myColsConPartRowLf:{
        width:40,
        alignItems:"center",
        justifyContent:"center"
    },
    myColsConPartRowRi:{
        flex:1,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        paddingRight:10,
        borderBottomWidth:1,
        borderColor:"#eee"
    },
    myColsConPartRowRi2R:{
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center"
    },
    iconMsg:{
        width:20,
        height:17
    },
    iconLinkman:{
        width:20,
        height:20,
        resizeMode:"stretch"
    },
    iconSettings:{
        width:22,
        height:21,
        resizeMode:"stretch"
    },
    iconArr2R:{
        width:8,
        height:14
    },
    icon22:{
        width:22,
        height:22
    },
    iconHelper:{
        width:22,
        height:22
    },
    iconAbout:{
        width:22,
        height:22
    },
    newMsgFlag:{
        borderRadius:10,
        height:20,
        width:30,
        textAlign:"center",
        backgroundColor:"red",
        fontSize:13,
        color:"white",
        lineHeight:20,
        marginRight:6
    },
    noSplitLine:{
        borderWidth:0
    }
});

export default styles;